// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDri3fXCr7TbRkVda9ont3HXB2jp4O7Bw',
    appId: '1:175240204876:web:277fc57b466fb7e0269ae9',
    messagingSenderId: '175240204876',
    projectId: 'fitbit-project-58078',
    authDomain: 'fitbit-project-58078.firebaseapp.com',
    storageBucket: 'fitbit-project-58078.firebasestorage.app',
    measurementId: 'G-RRBFGMH1KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiivmc2-kFsDby8cGBX68Ft1QURSPY2l8',
    appId: '1:175240204876:android:dcdb99cef409892e269ae9',
    messagingSenderId: '175240204876',
    projectId: 'fitbit-project-58078',
    storageBucket: 'fitbit-project-58078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLVlmp1NXhUUV1hABWvsASiHc8HzbJQQ',
    appId: '1:175240204876:ios:d6ae80ff637bbe08269ae9',
    messagingSenderId: '175240204876',
    projectId: 'fitbit-project-58078',
    storageBucket: 'fitbit-project-58078.firebasestorage.app',
    iosBundleId: 'com.example.fitbit',
  );
}
